### ISSUE TITLE
Add spec for missing file error

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#20]
Need to add spec to guard against future errors like this:

```sh
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-itu-0.2.1/lib/asciidoctor/itu/i18n-en.yaml
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:497:in `initialize'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:497:in `open'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:497:in `load_file'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-itu-0.2.1/lib/asciidoctor/itu/converter.rb:162:in `load_yaml'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.3.1/lib/asciidoctor/standoc/i18n.rb:26:in `i18n_init'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.3.1/lib/asciidoctor/standoc/base.rb:106:in `init'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-itu-0.2.1/lib/asciidoctor/itu/converter.rb:57:in `document'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.3.1/lib/asciidoctor/standoc/utils.rb:137:in `convert'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.14/lib/metanorma/input/asciidoc.rb:8:in `process'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-itu-0.2.1/lib/metanorma/itu/processor.rb:26:in `input_to_isodoc'
```

Originally at: https://github.com/metanorma/mn-samples-itu/pull/5#issuecomment-529401103

**Comment by opoudjis** [comment]
This is not user specified file, this is a core file in the gem, and Travis testing will have caught it. Nothing to action.

**Comment by ronaldtse** [comment]
@opoudjis it is a core file but clearly Travis hasn’t caught it. Are you sure it will be caught next time?

**Comment by opoudjis** [comment]
https://travis-ci.org/metanorma/metanorma-itu needs to be activated plox.

Once I get a chance to run Alex's scripts, now that we've discussed them, I will be able to find out. But Appveyor did catch it. Local rspec won't, because any missing files are in the dev environment.

**Comment by ronaldtse** [comment]
@opoudjis the correct link is Travis "com": https://travis-ci.com/metanorma/metanorma-itu .
