### ISSUE TITLE
Build failure since last PDF style sheet update

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#300]

**Comment by Intelligent2013** [comment]
First failed build was Aug 26, 2021 after https://github.com/metanorma/metanorma-itu/commit/8d8653ce0d1580edcd863971e65baa44e16d983b, but in the xslt there isn't reason for this.

It seems the issue relates to something another (may be relaton):
```
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected

/opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby -I/home/runner/work/metanorma-itu/metanorma-itu/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.10.1/lib:/home/runner/work/metanorma-itu/metanorma-itu/vendor/bundle/ruby/3.0.0/gems/rspec-support-3.10.2/lib /home/runner/work/metanorma-itu/metanorma-itu/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
Failures:

  1) Asciidoctor::ITU reorders references in bibliography, and renumbers citations accordingly
     Failure/Error:
       expect(xmlpp("<div>#{xpath.to_xml}</div>"))
         .to be_equivalent_to xmlpp(<<~"OUTPUT")
           <div>
             <docidentifier type='ITU'>ITU-T Y.1001</docidentifier>
             <docidentifier type='ITU'>ITU-T Y.140</docidentifier>
             <docidentifier type='ITU'>ITU-T Z.100</docidentifier>
             <docidentifier type='ISO'>ISO 55000:2014</docidentifier>
             <docidentifier type='URN'>urn:iso:std:iso:55000:stage-90.92:ed-1:en</docidentifier>
             <docidentifier type='ISO'>ISO/IEC 27001 (all parts)</docidentifier>
             <docidentifier type='URN'>urn:iso:std:iso-iec:27001</docidentifier>

       expected:
       <div>
         <docidentifier type='ITU'>ITU-T Y.1001</docidentifier>
         <docidentifier type='ITU'>ITU-T Y.140</docidentifier>
         <docidentifier type='ITU'>ITU-T Z.100</docidentifier>
         <docidentifier type='ISO'>ISO 55000:2014</docidentifier>
         <docidentifier type='URN'>urn:iso:std:iso:55000:stage-90.92:ed-1:en</docidentifier>
         <docidentifier type='ISO'>ISO/IEC 27001 (all parts)</docidentifier>
         <docidentifier type='URN'>urn:iso:std:iso-iec:27001</docidentifier>
         <docidentifier type='IEC'>IEC 60027</docidentifier>
         <docidentifier type='URN'>urn:iec:std:iec:60027::::en</docidentifier>
         <docidentifier type='Chinese Standard'>GB 12663-2019</docidentifier>
       </div>
       got:
       <div>
         <docidentifier type='ITU'>ITU-T Y.1001</docidentifier>
         <docidentifier type='ITU'>ITU-T Y.140</docidentifier>
         <docidentifier type='ITU'>ITU-T Z.100</docidentifier>
         <docidentifier type='IEC'>IEC 60027</docidentifier>
         <docidentifier type='URN'>urn:iec:std:iec:60027::::en</docidentifier>
         <docidentifier type='Chinese Standard'>GB 12663-2019</docidentifier>
         <docidentifier type='ISO'>ISO 55000</docidentifier>
         <docidentifier type='ISO'>ISO/IEC 27001</docidentifier>
       </div>
       Diff:

       @@ -2,12 +2,10 @@
          <docidentifier type='ITU'>ITU-T Y.1001</docidentifier>
          <docidentifier type='ITU'>ITU-T Y.140</docidentifier>
          <docidentifier type='ITU'>ITU-T Z.100</docidentifier>
       -  <docidentifier type='ISO'>ISO 55000:2014</docidentifier>
       -  <docidentifier type='URN'>urn:iso:std:iso:55000:stage-90.92:ed-1:en</docidentifier>
       -  <docidentifier type='ISO'>ISO/IEC 27001 (all parts)</docidentifier>
       -  <docidentifier type='URN'>urn:iso:std:iso-iec:27001</docidentifier>
          <docidentifier type='IEC'>IEC 60027</docidentifier>
          <docidentifier type='URN'>urn:iec:std:iec:60027::::en</docidentifier>
          <docidentifier type='Chinese Standard'>GB 12663-2019</docidentifier>
       +  <docidentifier type='ISO'>ISO 55000</docidentifier>
       +  <docidentifier type='ISO'>ISO/IEC 27001</docidentifier>
        </div>
     # ./spec/asciidoctor/base_spec.rb:1800:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.0.0/gems/vcr-5.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # ./vendor/bundle/ruby/3.0.0/gems/vcr-5.0.0/lib/vcr.rb:188:in `use_cassette'
     # ./spec/asciidoctor/base_spec.rb:1770:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:44:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:44:in `chdir'
     # ./spec/spec_helper.rb:44:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:43:in `block (2 levels) in <top (required)>'

Finished in 39.35 seconds (files took 2.41 seconds to load)
129 examples, 1 failure

Failed examples:

rspec ./spec/asciidoctor/base_spec.rb:1762 # Asciidoctor::ITU reorders references in bibliography, and renumbers citations accordingly

Coverage report generated for RSpec to /home/runner/work/metanorma-itu/metanorma-itu/coverage. 1315 / 1350 LOC (97.41%) covered.
```

**Comment by opoudjis** [comment]
@ronaldtse @Intelligent2013 No need to raise these, they will go away when I do integration testing for each release. XSL pushes regularly reveal emerging inconsistencies; this particular instance was because of an update to relaton, and it has already been resolved in the spec files.
