### ISSUE TITLE
Failure when working with `NotoSansCJK-Regular.ttc`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#327]
Reported by @bquast at ITU (https://github.com/metanorma/mn-samples-itu/issues/149):

This is a trace from ArchLinux, perhaps Fontist is not compatible with ArchLinux?

```
not a TTC file
Warning: File at /usr/share/fonts/noto/NotoSansCJK-Regular.ttc not recognized as a font file.
not a TTC file
Warning: File at /usr/share/fonts/noto/NotoSerifCJK-Regular.ttc not recognized as a font file.
/usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `block in changed?': undefined method `[]' for #<IO:<STDOUT>> (NoMethodError)
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `changed?'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:120:in `block in do_build_index'
	from <internal:kernel>:90:in `tap'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:119:in `do_build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:108:in `block in build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/utils/locking.rb:11:in `lock'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:107:in `build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:94:in `index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:77:in `find'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:71:in `find_by_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:63:in `find_styles'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:52:in `find_styles'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:74:in `find_font_with_name'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/install.rb:16:in `file_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:51:in `block in style_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `flat_map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `style_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:45:in `style_paths_map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:40:in `block in font_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `font_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:26:in `call'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:21:in `from_hash'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:47:in `fontist_install'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:28:in `install_fonts_safe'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:95:in `install_fonts'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/compile_options.rb:57:in `font_install'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/compile.rb:36:in `compile'
```

**Comment by CAMOBAP** [comment]
Investigated in https://github.com/metanorma/mn-samples-itu/issues/149 and https://github.com/fontist/fontist/issues/302 created for future fix

**Comment by ronaldtse** [comment]
Thanks for closing!
